FROM docker.elastic.co/elasticsearch/elasticsearch:5.2.1

MAINTAINER AndriynomeD <andriynomed.work@gmail.com>

RUN elasticsearch-plugin install analysis-phonetic
RUN elasticsearch-plugin install analysis-icu
