FROM docker.elastic.co/elasticsearch/elasticsearch:6.8.15

MAINTAINER AndriynomeD <andriynomed.work@gmail.com>

RUN elasticsearch-plugin install analysis-phonetic
RUN elasticsearch-plugin install analysis-icu
